config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :restaurants
  resources :reservations
  root 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer, class_name: "User", foreign_key: "user_id"
  belongs_to :reserved_restaurant, class_name: "Restaurant", foreign_key: "restaurant_id"

  validates :party_size, :user_id, :restaurant_id, :date, :timeslot, presence: true, allow_nil: false
  validates :party_size, numericality: {greater_than: 0}
  validate :party_size_less_than_capacity
  validate :date_greater_than_or_equal_to_today

  private

  def party_size_less_than_capacity
    if timeslot == nil || date == nil || party_size == nil
    else
    if id

      total_reservations = Reservation.where(timeslot: timeslot, date: date, restaurant_id: restaurant_id).sum(:party_size)
      capacity = Restaurant.find(restaurant_id).capacity

      available_capacity = capacity - total_reservations + Reservation.where(id: id).sum(:party_size)

      restaurant = Restaurant.find(restaurant_id).name

      errors.add(restaurant, 'does not have enough space for this number of guests!') if party_size >  available_capacity
    else

    total_reservations = Reservation.where(timeslot: timeslot, date: date, restaurant_id: restaurant_id).sum(:party_size)
    capacity = Restaurant.find(restaurant_id).capacity
    available_capacity = capacity - total_reservations

    restaurant = Restaurant.find(restaurant_id).name

    errors.add(restaurant, 'does not have enough space for this number of guests!') if party_size >  available_capacity

    end
  end
  end

  def date_greater_than_or_equal_to_today
    # if date == nil
    # else
      errors.add(:date, 'cannot be before today') if date.present? && Date.parse(date.to_s) < Date.today
    # end
  end

 end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reservations

  # suggestion: just call these "users"
  # has_many :users, through: :reservations
  has_many :customers, through: :reservations, source: :user

  belongs_to :owner, class_name: "User", foreign_key: "user_id"

  validates :name, :capacity, :street_name, :neighbourhood, :postal_code, :city, :province, :country, :cuisine_type, :phone_number, :email, :price, :summary, :user_id, presence: true

    def timeslot_check(time_slot, restaurant_id, date)

      total_reservations = Reservation.where(timeslot: time_slot, date: date, restaurant_id: restaurant_id).sum(:party_size)
      capacity = Restaurant.find(restaurant_id).capacity
      available_capacity = capacity - total_reservations
        if available_capacity > 10
          p "Available"
        elsif available_capacity > 0 && available_capacity <= 10
          p "#{available_capacity} seats available"
        else
          p "Unavailable"
        end
      end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
  has_many :reserved_restaurants, through: :reservations, source: :restaurant
  has_many :owned_restaurants, class_name: "Restaurant"
  has_secure_password

  validates :name, :phone_number, :email, presence: true
  validates :phone_number, numericality: {only_integer: true}
  validates :phone_number, :email, uniqueness: true


  validates :password, presence: true, confirmation: true, :unless => :already_has_password?
#
private
    def already_has_password?
      !self.password_digest.blank?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session["user_id"]) if session[:user_id]
  end
  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please Log In or Sign Up"
      redirect_to new_session_url
    end
  end
  helper_method :current_user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController


  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @restaurant = Restaurant.find(params[:reservation][:restaurant_id])

    if @reservation.save
      redirect_to reservation_path(@reservation)
    else
      @timeslots = ["11-12", "12-1", "1-2", "2-3", "3-4", "4-5", "5-6", "6-7", "7-8", "8-9"]
      redirect_to(restaurant_path(@restaurant), {:flash => { :reservation_errors => @reservation.errors.full_messages }})
    end

  end

  def index
    @reservations = Reservation.all
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to restaurants_path, :notice => "Your reservation has been deleted."
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])

    if @reservation.update_attributes(reservation_params)
      redirect_to reservation_url(@reservation), :notice => "Your reservation has been successfully updated!"
    else
      # render :edit
      redirect_to(edit_reservation_path(@reservation), {:flash => { :reservation_errors => @reservation.errors.full_messages }})
    end
  end

  private
  def reservation_params
    params.require(:reservation).permit(:user_id, :restaurant_id, :timeslot, :party_size, :date)
  end
 end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    begin
      puts "Logging out reservation"
      puts @reservation
    rescue
      puts "No reservation instance"
    end

    @restaurant = Restaurant.find(params[:id])
    @timeslots = ["11-12", "12-1", "1-2", "2-3", "3-4", "4-5", "5-6", "6-7", "7-8", "8-9"]

    if params[:date]
      @date = params[:date]
    else
      @date = Date.today
    end

    @reservation = Reservation.new

  end

  def new
     @restaurant = Restaurant.new
   end

   def create
     @restaurant = Restaurant.new(restaurant_params)
   end

   def update

     @restaurant = Restaurant.find(params[:id])
     @timeslots = ["11-12", "12-1", "1-2", "2-3", "3-4", "4-5", "5-6", "6-7", "7-8", "8-9"]

     if params[:date]
       @date = params[:date]
     else
       @date = Date.today
     end

     @reservation = Reservation.new

     render 'show'
   end


private
  def restaurant_params
      params.require(restaurant).permit(:name, :capacity, :street_name, :neighbourhood, :postal_code, :city, :province, :country, :cuisine_type, :phone_number,
      :email, :price, :summary, :menu)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_path, :notice => "Successfully logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
      @user = User.new
  end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to restaurants_path, notice: "Signed up!"
      else
        render :new
      end
    end

    def show
      @user = User.find(params[:id])
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])

      if @user.update_attributes(user_params)
        redirect_to user_url(@user)
      else
        render :edit
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to root
    end


    private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeatYourself</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Caveat+Brush" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sansita" rel="stylesheet">
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'header_footer' %>
  </head>
  <header>
    <div class="root">
      <h1> <%= link_to 'Seat Yourself', root_url %></h1>
    </div>
    <div class="links">
      <% if current_user %>
      <p><span class="login-link"> Signed in as <%= link_to current_user.name.capitalize, user_path(current_user.id) %>, </span> &nbsp; &nbsp;<%= link_to 'Log out', session_path("current"), :method => :delete %> </p>
      <% else %>
      <p><%= link_to 'Log In', new_session_url %>    |    <%= link_to 'Sign Up', new_user_url %></p>
      <% end %><br>
    </div>
  </header>

  <body>
    <% if flash[:notice] %>
     <p id="notice"><%= flash[:notice] %></p>
   <% end %>
   <% if flash[:alert] %>
     <p id="alert"><%= flash[:alert] %></p>
   <% end %>
    <%= yield %>

  </p>
  </body>
  <footer>
    <p>© Akshit Sahani, Richard Strauss, Matthew Evershed, Justin Cheung, Leon Chung</p>
  </footer>
</html>

app/views/reservations/edit.html.erb
<% if flash[:reservation_errors] %>
   <div id="error_explanation">
     <p>Please address the following <%= pluralize(flash[:reservation_errors].count, "error") %> before resubmitting your request to change your reservation:</h2>

     <ul>
     <%flash[:reservation_errors].each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

<%= form_for @reservation do |f| %>
 <%= f.label :party_size %>
 <%= f.number_field :party_size %>

 <%= f.label :date %>
 <%= f.date_field :date %>

 <%= f.hidden_field :user_id, :value => session[:user_id] %>


<%= f.label :timeslot %>
<%= f.select :timeslot, ['11-12', '12-1', '1-2', '2-3', '3-4', '4-5', '5-6', '6-7', '7-8', '8-9']%>
<%= f.submit "Edit a reservation" %>

<% end %>

app/views/reservations/show.html.erb
Reservation successfully created! <br> <br>

<div class="reservation-container">
You have a reservation at <%= @reservation.reserved_restaurant.name %> for <%= @reservation.party_size %> people between <%= @reservation.timeslot %> pm. <br> <br>
We hope you enjoy your meal!
</div>

app/views/restaurants/index.html.erb
<main>
  <div class="hero-image">
<span class="chef-image">    <%= image_tag("chefs-table.jpg") %> </span>
    <h1 class="hero-title"> SEAT <span class="yourself">YOURSELF</span> </h1>
</div>
<% @restaurants.each do |r| %>
<div class='all-restaurants'>
  <%= link_to restaurant_path(r) do %><br>
  <%=image_tag(r.image_1, :alt => "restaurant", height: 150, width: 150)%>    <br>
  <div class="restaurant-info">
  <p class="restaurant-name"><%= r.name%></p>

  <p><%=r.neighbourhood %> | <%= r.cuisine_type %><br><br><br><br></p>
  <p class="restaurant-price"><%= r.price %></p>
  </div>
</div>
<% end %>
</a>
<% end %>

</main>

<%= stylesheet_link_tag 'homepage' %>

app/views/restaurants/show.html.erb
    <%= stylesheet_link_tag 'application' %>



<!--  This is a workaround for us to be able to pass the errors around. -->
<% if flash[:reservation_errors] %>
   <div id="error_explanation">
    <p>Please address the following error(s) before resubmitting your reservation:</p>
     <ul>
     <%flash[:reservation_errors].each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

<div class="restaurant_container">
<div class="restaurant_image_container">
  <%= image_tag(@restaurant.image_1, :alt => "restaurant", class: "restaurant_top_image", width: "48%") %>
</div>
<div class="restaurant_details_container">
<div class="restaurant_details_header">
<div class="restaurant_title">
<h1><%= @restaurant.name %><br></h1>
<%= @restaurant.neighbourhood %>, <%= @restaurant.city %>, <%=@restaurant.country %>
</div>
<div class="restaurant_attributes">
  <%= @restaurant.price %>
  <br>
  <%= @restaurant.cuisine_type %>
</div>
</div>
<br><br>
<div class="restaurant_details_summary"><%= @restaurant.summary %></div>
<br><br><br>
<br>
<br>
<div class="restaurant_details_footer"><b>
<%= @restaurant.street_name %>, <%= @restaurant.postal_code %>, <%= @restaurant.city %>,
<%= @restaurant.province %>, <%=@restaurant.country %>
<br>

<%= @restaurant.email %>
<%= @restaurant.phone_number %>
<br>
</b>
</div>
</div>
</div>


<div class="available">
  <div class="date_container">
    <div class="date_header_container">
      <h2> Availability </h2>
    <div class="chosen_date">
      <p> Date: <%= @date %> </p>
    </div>
    <div class="select_date">
    <%= form_tag do %>
      <input type="hidden" name="_method" value="patch">
      <label for="date">Change date:</label>
      <input type="date" name="date" id="date" value="date">
      <input type="submit" value="Check">
    <% end %>
    </div>
  </div>
    <div class="timeslots">

  <% @timeslots.each do |t| %>
  <% time_slot = t %>
  <%= time_slot %> pm:
  <%= @restaurant.timeslot_check(time_slot, @restaurant.id, @date) %>
  <br>
  <% end %>
  </div>
  </div>

  <div class="reservation">
    <h2>Make a reservation</h2>

    <br><br><br><br><br><br>

      <%= form_for @reservation do |f| %>
       <%= f.label :party_size %>
       <%= f.number_field :party_size %>

       <%= f.label :date %>
       <%= f.date_field :date %>

       <%= f.hidden_field :user_id, :value => session[:user_id] %>
       <%= f.hidden_field :restaurant_id, :value => @restaurant.id %>

      <%= f.label :timeslot %>
      <%= f.select :timeslot, @timeslots%>

      <%= f.submit "Make a reservation" %>

      <% end %> <br><br><br><br><br><br>
  </div>


</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
 <div id="error_explanation">
   <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>

   <ul>
   <% @user.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
 <% end %>

<%= form_for @user do |f| %>

<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :email %>
  <%= f.text_field :email %>
</p>
<p>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
</p>
<div>
  <%= f.submit "Update information" %>
</div>
<% end %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
 <div id="error_explanation">
   <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>

   <ul>
   <% @user.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
<% end %>
<br>
<em> Welcome to Seat Yourself, your go-to for all reservations from now on!</em>
<div class="signupform">
<h1>Sign Up</h1><br><br>
<div class="info">
  <%= form_for @user do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </p>
  <div class="signup">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<% if current_user.id == @user.id %>
<h1><%= @user.name.capitalize %>'s Account Details</h1>
<p>Phone Number : <%= @user.phone_number %><br>
Email : <%= @user.email %></p>
<p><%= link_to "Edit User Info", edit_user_path(@user) %>

<div>
<h1>Reservations</h1>
  <% @user.reservations.each do |r| %>
<div class="reservation-container">
  <p> Restaurant : <%= r.reserved_restaurant.name %><br>
  Reservation Time : <%= r.timeslot %><br>
  Party Size : <%= r.party_size %><br>
  Reservation Date : <%= r.date %><br>
</p>
<p><%= link_to "Edit Reservation", edit_reservation_path(r) %> | <%= link_to "Delete Reservation", reservation_path(r), method: :delete, data: {confirm: "Are you sure you want to delete this reservation?"} %></p>
</div><br>
  <% end %>
<% else %>
  <h2> Sorry, you do not have access to this account. </h2>
  <% end %>
</div>